export type Game = {
  slug: string;
  title: string;
  genre: string;
  description: string;
  itchSlug: string;
  tags: string[];
};

export const games: Game[] = [
  {
    slug: "dream-land",
    title: "Dream Land",
    genre: "Adventure",
    description: "Rüya dünyasında geçen bir macera oyunu.",
    itchSlug: "dream-land",
    tags: ["adventure"],
  },
  {
    slug: "what-the-duck",
    title: "What The Duck",
    genre: "Adventure",
    description: "Ördeklerle dolu sürpriz dolu bir macera.",
    itchSlug: "what-the-duck",
    tags: ["adventure", "funny"],
  },
  {
    slug: "annie-3",
    title: "Annie 3",
    genre: "Horror",
    description: "Serinin üçüncü bölümü. Karanlık bir korku deneyimi.",
    itchSlug: "annie-3",
    tags: ["horror"],
  },
  {
    slug: "mini-pekka-vs-sneaky-golem",
    title: "Mini Pekka vs Sneaky Golem",
    genre: "Action",
    description: "Battle for the Pancake — epik bir mücadele.",
    itchSlug: "mini-pekka-vs-sneaky-golem-battle-for-the-pancake",
    tags: ["action", "battle"],
  },
  {
    slug: "platform",
    title: "PLATFORM",
    genre: "Platformer",
    description: "Klasik platform oyunu deneyimi.",
    itchSlug: "platform",
    tags: ["platformer"],
  },
  {
    slug: "star-swipe",
    title: "STAR SWIPE",
    genre: "Action",
    description: "Yıldızlar arasında hızlı refleks gerektiren bir oyun.",
    itchSlug: "star-swipe",
    tags: ["action"],
  },
  {
    slug: "mysterious-game",
    title: "Mysterious Game",
    genre: "Adventure",
    description: "Gizemlerin peşinden giden bir macera.",
    itchSlug: "mysterious-game",
    tags: ["adventure", "mystery"],
  },
  {
    slug: "reality-threshold",
    title: "Reality Threshold",
    genre: "Adventure",
    description: "Gerçeklik sınırında geçen gerilim dolu bir yolculuk.",
    itchSlug: "reality-threshold",
    tags: ["adventure", "thriller"],
  },
  {
    slug: "call-of-gaia",
    title: "Call Of Gaia",
    genre: "Adventure",
    description: "Gaia'nın çağrısına cevap ver. Doğanın sesi seni bekliyor.",
    itchSlug: "call-of-gaia",
    tags: ["adventure", "nature"],
  },
  {
    slug: "unfinished-tale",
    title: "Unfinished Tale",
    genre: "Adventure",
    description: "Don't Starve Together esinli bir hayatta kalma macerası.",
    itchSlug: "unfinished-tale",
    tags: ["adventure", "survival"],
  },
  {
    slug: "secret-underground",
    title: "Secret Underground",
    genre: "Adventure",
    description:
      "Kontrol altına alınmayan tehlikeli bir robot yeraltı dünyası, yüzeyi karanlığa sürükleyebilir.",
    itchSlug: "secret-underground",
    tags: ["adventure", "sci-fi"],
  },
  {
    slug: "annie-2",
    title: "Annie 2",
    genre: "RPG",
    description: "Annie serisinin ikinci bölümü. Rol yapma oyunu.",
    itchSlug: "annie-2",
    tags: ["rpg", "horror"],
  },
  {
    slug: "the-silent-depths",
    title: "The Silent Depths DLC",
    genre: "Adventure",
    description: "Sessizliğin derinliklerine inen DLC bölümü.",
    itchSlug: "the-silent-depths-dlc-edition",
    tags: ["adventure", "dlc"],
  },
  {
    slug: "alone-duck",
    title: "Alone Duck",
    genre: "Adventure",
    description: "Yalnız bir ördek olarak dünyayı keşfet.",
    itchSlug: "alone-duck",
    tags: ["adventure", "casual"],
  },
  {
    slug: "prison-duck",
    title: "Prison Duck",
    genre: "Adventure",
    description: "Hapishaneden kaçmaya çalışan bir ördek.",
    itchSlug: "prison-duck",
    tags: ["adventure", "escape"],
  },
  {
    slug: "elden-robot",
    title: "Elden Robot",
    genre: "Action RPG",
    description: "Elden Ring tarzında indie bir oyun. Soulslike deneyimi.",
    itchSlug: "elden-robot",
    tags: ["action", "rpg", "soulslike"],
  },
  {
    slug: "diamondsion",
    title: "DIAMONDSION",
    genre: "Puzzle",
    description: "Elmas boyutunda bulmaca çözme macerası.",
    itchSlug: "diamondsion",
    tags: ["puzzle"],
  },
  {
    slug: "anteaters-coffee-simulator",
    title: "AntEaters Coffee Simulator",
    genre: "Simulation",
    description: "Karıncayiyen kahve simülatörü. Beklenmedik bir deneyim.",
    itchSlug: "anteaters-coffe-simulator",
    tags: ["simulation", "funny"],
  },
  {
    slug: "syntos",
    title: "Syntos",
    genre: "Action",
    description: "Aksiyon dolu bir Syntos deneyimi.",
    itchSlug: "syntos",
    tags: ["action"],
  },
  {
    slug: "annie",
    title: "Annie",
    genre: "Adventure",
    description: "Terk edilmiş bir kasabada terk edilmiş bir kişiyle karşılaşıyorsunuz.",
    itchSlug: "annie",
    tags: ["adventure", "story"],
  },
  {
    slug: "big-stick",
    title: "Big Stick",
    genre: "Adventure",
    description: "Büyük bir sopayla maceraya atıl.",
    itchSlug: "big-stick",
    tags: ["adventure", "action"],
  },
  {
    slug: "infinity-duck",
    title: "Infinity Duck",
    genre: "Adventure",
    description: "Sonsuz ördek macerası.",
    itchSlug: "infinity-duck",
    tags: ["adventure", "casual"],
  },
  {
    slug: "escape-ball",
    title: "Escape Ball",
    genre: "Platformer",
    description: "Top olarak platformlardan kaç.",
    itchSlug: "escape-ball",
    tags: ["platformer"],
  },
  {
    slug: "stuck-in-console",
    title: "Stuck in Console",
    genre: "Adventure",
    description: "Konsolun içinde sıkışan bir karakterin hikayesi.",
    itchSlug: "stuck-in-console",
    tags: ["adventure", "meta"],
  },
  {
    slug: "amon-din",
    title: "Amon Din",
    genre: "Adventure",
    description: "Amon Din dünyasında geçen bir macera.",
    itchSlug: "amon-din",
    tags: ["adventure"],
  },
  {
    slug: "dead-or-live",
    title: "Dead Or Live",
    genre: "Puzzle",
    description: "Ölüm mü yaşam mı? Bulmacaları çözerek karar ver.",
    itchSlug: "dead-or-live",
    tags: ["puzzle", "thriller"],
  },
  {
    slug: "silent-alien",
    title: "Silent Alien",
    genre: "Survival",
    description: "Sessiz uzaylılardan hayatta kalmaya çalış.",
    itchSlug: "silent-alien",
    tags: ["survival", "sci-fi"],
  },
  {
    slug: "little-mission",
    title: "Little Mission",
    genre: "Adventure",
    description: "Küçük ama önemli bir görev.",
    itchSlug: "little-mission",
    tags: ["adventure"],
  },
  {
    slug: "cursed-ghoul",
    title: "Cursed Ghoul",
    genre: "Adventure",
    description: "Lanetlenmiş ghoul olarak karanlıkta yürü.",
    itchSlug: "cursed-ghoul",
    tags: ["adventure", "horror"],
  },
  {
    slug: "witch-of-the-nature",
    title: "Witch of the Nature",
    genre: "Adventure",
    description: "Doğanın cadısı olarak büyü ve keşfet.",
    itchSlug: "witch-of-the-nature",
    tags: ["adventure", "magic"],
  },
  {
    slug: "endless-deathly-hallow",
    title: "Endless Deathly Hallow",
    genre: "Adventure",
    description: "Sonsuz ölüm gölgesinde hayatta kal.",
    itchSlug: "endless-deathly-hallow",
    tags: ["adventure", "dark"],
  },
  {
    slug: "pier-mage",
    title: "Pier Mage",
    genre: "Adventure",
    description: "Hikayeli bir indie oyun. İskele büyücüsünün yolculuğu.",
    itchSlug: "pier-mage",
    tags: ["adventure", "story", "magic"],
  },
  {
    slug: "robotica",
    title: "ROBOTİCA",
    genre: "Adventure",
    description: "Robot dünyasında geçen bir macera.",
    itchSlug: "robotica",
    tags: ["adventure", "sci-fi"],
  },
  {
    slug: "mafia-duck",
    title: "Mafia Duck",
    genre: "Adventure",
    description: "Mafya ördek dünyasının karanlık hikayeleri.",
    itchSlug: "mafia-duck",
    tags: ["adventure", "crime"],
  },
  {
    slug: "pix-in-game",
    title: "Pix İn Game",
    genre: "Adventure",
    description: "Piksel dünyasında oyun içinde oyun deneyimi.",
    itchSlug: "pix-in-game",
    tags: ["adventure", "meta", "pixel"],
  },
  {
    slug: "arabventure",
    title: "ArabVenture",
    genre: "Adventure",
    description: "Arap dünyasında geçen egzotik bir macera.",
    itchSlug: "arabventure",
    tags: ["adventure"],
  },
  {
    slug: "back-jump",
    title: "BACK JUMP",
    genre: "Platformer",
    description: "Back jump — platform oyununun sıradışı yorumu.",
    itchSlug: "back-jump",
    tags: ["platformer"],
  },
  {
    slug: "pixelren",
    title: "Pixelren",
    genre: "Action",
    description: "Evrensel düzeni koruyan piksel savaşçının hikayesi.",
    itchSlug: "pixelren",
    tags: ["action", "pixel"],
  },
  {
    slug: "turtle-adventure",
    title: "Turtle Adventure",
    genre: "Adventure",
    description: "Kaplumbağanın epik macera yolculuğu.",
    itchSlug: "turtle-advanture",
    tags: ["adventure", "casual"],
  },
];

export function getGameBySlug(slug: string): Game | undefined {
  return games.find((g) => g.slug === slug);
}
